Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('entities.urls', namespace='entities'))
]

Hospital/entities/urls.py
"""
This module contains the urls for the 'entities' app.
"""
from django.urls import path
from entities.views.doctor import DoctorListView, DoctorDetailView
from entities.views.nurse import NurseListView, NurseDetailView
from entities.views.patient import PatientListView, PatientDetailView
from entities.views.room import RoomListView, RoomDetailView, RoomDeleteView
from entities.views.homepage import HomepageView

app_name = 'entities'

urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("doctors/", DoctorListView.as_view(), name='list_doctor'),
    path("doctors/<int:pk>/", DoctorDetailView.as_view(),
         name='detail_doctor'),
    #  TODO: fix the below views
    path("nurses/", NurseListView.as_view(), name='list_nurse'),
    path("nurses/<int:pk>/", NurseDetailView.as_view(), name='detail_nurse'),
    path("patients/", PatientListView.as_view(), name='list_patient'),
    path("patients/<int:pk>/",
         PatientDetailView.as_view(),
         name='detail_patient'),
    path("rooms/", RoomListView.as_view(), name='list_room'),
    path("rooms/<int:pk>/", RoomDetailView.as_view(), name='detail_room'),
    path("rooms/<int:pk>/", RoomDeleteView.as_view(), name='delete_room'),
]

Hospital/entities/models.py
"""
Here is the file that contains all the entity models.
"""
from django.db.models import (Model, CharField, PositiveIntegerField,
                              DecimalField, ForeignKey, SET_NULL, RESTRICT)
from django.core.validators import MaxValueValidator, MinValueValidator

# TODO: Add dockstrings


# ========= Base Models =========
class Human(Model):
    """Is the base for all people. Does the validations too."""
    name: CharField = CharField(max_length=40, null=False, blank=False)
    age: PositiveIntegerField = PositiveIntegerField(
        null=False, validators=[MinValueValidator(0),
                                MaxValueValidator(110)])

    class Meta:
        abstract = True


class Employee(Human):
    """
    Is the base for workers, like class Human it has validators that ensure
    the proper results for the workers.
    """
    age = PositiveIntegerField(
        null=False, validators=[MinValueValidator(21),
                                MaxValueValidator(67)])
    experience: PositiveIntegerField = PositiveIntegerField(null=False)
    salary: DecimalField = DecimalField(null=False,
                                        decimal_places=2,
                                        max_digits=10)

    class Meta:
        abstract = True


# ========= Entity Models =========
class Room(Model):
    """The model for the room"""
    number: PositiveIntegerField = PositiveIntegerField(
        null=False, unique=True, validators=[MinValueValidator(0)])
    capacity: PositiveIntegerField = PositiveIntegerField(
        null=False, validators=[MinValueValidator(1),
                                MaxValueValidator(4)])

    class Meta:
        verbose_name_plural = "Rooms"

    def __str__(self):
        return f"Room: {self.number}"


# TODO: validate the experience based on it's age.
class Doctor(Employee):
    """The model for the doctor entity."""

    class Meta:
        verbose_name_plural = "Doctors"

    def __str__(self):
        return f"Doctor: {self.name}"


class Nurse(Employee):
    """The model for the nurse entity."""
    room_in_charge: ForeignKey = ForeignKey(Room,
                                            null=True,
                                            on_delete=SET_NULL)

    class Meta:
        verbose_name_plural = "Nurses"

    def __str__(self):
        return f"Nurse: {self.name}"


class Patient(Human):
    """The model for the patient entity."""
    disease: CharField = CharField(max_length=60, null=False, blank=False)
    # The patient won't be deleted incase the room is deleted.
    room: ForeignKey = ForeignKey(Room, null=False, on_delete=RESTRICT)
    # The patient won't be deleted incase the doctor is deleted.
    doctor: ForeignKey = ForeignKey(Doctor, null=False, on_delete=RESTRICT)

    class Meta:
        verbose_name_plural = "Patients"

    def __str__(self):
        return f"Patient: {self.name}"

Hospital/entities/views/doctor.py
"""
This module contains the doctor views of the entities app.
"""
from typing import Any
from django.db.models import Count, Avg
from django_filters.views import FilterView
from django.views.generic import DetailView
from entities.models import Doctor, Patient
from entities.filters.doctor import DoctorFilter


class DoctorListView(FilterView):
    model = Doctor
    queryset = Doctor.objects.annotate(num_patients=Count('patient')).all()
    filterset_class = DoctorFilter
    context_object_name = 'context'
    template_name = 'content/doctor/list/index.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        ctx: dict[str, Any] = super().get_context_data(**kwargs)
        doctors = ctx.pop("context")
        ctx["context"] = {
            "filter":
            self.filterset_class,
            "doctors":
            doctors,
            "total_doctors":
            self.object_list.count(),
            "average_salary":
            (self.object_list.aggregate(avg_salary=Avg('salary'))['avg_salary']
             or 0),
            "average_doctor_patients": (self.object_list.aggregate(
                avg_patient=Avg('num_patients'))['avg_patient'] or 0),
            "average_experience": (self.object_list.aggregate(
                avg_experience=Avg('experience'))['avg_experience'] or 0)
        }

        return ctx


class DoctorDetailView(DetailView):
    model = Doctor
    context_object_name = 'context'

    template_name = "content/doctor/detail/index.html"

    def get_context_data(self, **kwargs):
        context = super(DoctorDetailView, self).get_context_data(**kwargs)
        doctor = context.pop("context")
        context["context"] = {
            "doctor": doctor,
            "patients": Patient.objects.filter(doctor=doctor)
        }

        return context

Hospital/entities/views/homepage.py
"""
This view contains the hompage view.
"""
from django.views.generic import (
    TemplateView,
    # ListView,
    # DetailView,
    # CreateView,
    # UpdateView,
    # DeleteView,
    # FormView,
)


class HomepageView(TemplateView):
    """This view is for the homepage"""
    template_name = 'index.html'

Hospital/entities/views/nurse.py
"""
This module contains the nurse views of the entities app.
"""
from typing import Any
from django.db.models import Avg, Count
from django_filters.views import FilterView
from django.views.generic import DetailView
from entities.models import Nurse, Patient
from entities.filters.nurse import NurseFilter


class NurseListView(FilterView):
    model = Nurse
    queryset = Nurse.objects.select_related('room_in_charge').annotate(
        patients_num=Count('room_in_charge__patient'))
    filterset_class = NurseFilter
    context_object_name = "context"
    template_name = "content/nurse/list/index.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx: dict[str, Any] = super().get_context_data(**kwargs)
        nurses = ctx.pop("context")
        ctx["context"] = {
            "filter":
            self.filterset_class,
            "nurses":
            nurses,
            "total_nurses":
            self.object_list.count(),
            "average_salary":
            (self.object_list.aggregate(avg_salary=Avg("salary"))["avg_salary"]
             or 0),
            "average_experience": (self.object_list.aggregate(
                avg_experience=Avg("experience"))["avg_experience"] or 0)
        }

        return ctx


class NurseDetailView(DetailView):
    model = Nurse
    context_object_name = "context"
    template_name = "content/nurse/detail/index.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super(NurseDetailView, self).get_context_data(**kwargs)
        nurse = ctx.pop("context")
        ctx["context"] = {
            "nurse": nurse,
            "patients": Patient.objects.filter(room=nurse.room_in_charge)
        }
        return ctx

Hospital/entities/views/patient.py
"""
This module contains the patient views of the entities app.
"""
from typing import Any
from django.db.models import Avg
from django.views.generic import DetailView
from django_filters.views import FilterView
from entities.models import Patient, Nurse
from entities.filters.patient import PatientFilter


class PatientListView(FilterView):
    model = Patient
    queryset = Patient.objects.all()
    filterset_class = PatientFilter
    context_object_name = "context"
    template_name = "content/patient/list/index.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx: dict[str, Any] = super().get_context_data(**kwargs)
        patients = ctx.pop("context")
        ctx["context"] = {
            "filter":
            self.filterset_class,
            "patients":
            patients,
            "total_patients":
            self.object_list.count(),
            "average_age":
            (self.object_list.aggregate(avg_age=Avg("age"))["avg_age"] or 0),
        }
        return ctx


class PatientDetailView(DetailView):
    model = Patient
    context_object_name = "context"
    template_name = "content/patient/detail/index.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super(PatientDetailView, self).get_context_data(**kwargs)
        patient = ctx.pop("context")
        ctx["context"] = {
            "patient": patient,
            "nurses": Nurse.objects.filter(room_in_charge=patient.room)
        }
        return ctx

Hospital/entities/views/room.py
"""
This module contains the Room views of the entities app.
"""
from typing import Any
from django.urls import reverse_lazy
from django.db.models import Avg, Count, F, Sum
from django.views.generic import DetailView, DeleteView
from django_filters.views import FilterView
from entities.models import Room, Nurse, Patient
from entities.filters.room import RoomFilter


class RoomListView(FilterView):
    model = Room
    queryset = (Room.objects.all().annotate(
        reserved_beds=Count('patient')).annotate(
            free_beds=F('capacity') -
            F('reserved_beds')).annotate(num_nurses=Count('nurse')).annotate(
                num_patients=Count('patient')))
    filterset_class = RoomFilter
    context_object_name = "context"
    template_name = "content/room/list/index.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx: dict[str, Any] = super().get_context_data(**kwargs)
        rooms = ctx.pop("context")
        ctx["context"] = {
            "filter":
            self.filterset_class,
            "rooms":
            rooms,
            "total_rooms":
            self.object_list.count(),
            "average_capacity": (self.object_list.aggregate(
                avg_capacity=Avg("capacity"))["avg_capacity"] or 0),
            "total_beds": (self.object_list.aggregate(
                total_beds=Count("capacity"))["total_beds"] or 0),
            "total_free_beds": (self.object_list.aggregate(
                total_free_beds=Sum("free_beds"))["total_free_beds"] or 0)
        }
        return ctx


class RoomDetailView(DetailView):
    model = Room
    context_object_name = "context"
    template_name = "content/room/detail/index.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super(RoomDetailView, self).get_context_data(**kwargs)
        room = ctx.pop("context")
        num_of_patients = len(Patient.objects.filter(room=room))
        num_of_nurses = len(Nurse.objects.filter(room_in_charge=room))
        ctx["context"] = {
            "room": room,
            "num_patients": num_of_patients,
            "free_beds": room.capacity - num_of_patients,
            "num_nurses": num_of_nurses,
            "nurses": Nurse.objects.filter(room_in_charge=room),
            "patients": Patient.objects.filter(room=room)
        }
        return ctx


class RoomDeleteView(DeleteView):
    model = Room
    success_url = reverse_lazy("entities:list_room")

Hospital/entities/templates/content/room/detail/index.html
{% extends "base.html" %} {% block content %}

<div class="ListContent">
  <div class="Card">
    <div class="Header">Room</div>
    <div class="Body">
      <div class="Card">
        <div class="Header">Room Info</div>
        <div class="Body">
          <div class="BasicData">
            <table class="VerticalTable">
              <tbody>
                <tr>
                  <th>Number</th>
                  <td>{{context.room.number}}</td>
                </tr>
                <tr>
                  <th>Capacity</th>
                  <td>{{context.room.capacity}}</td>
                </tr>
                <tr>
                  <th>Number of Patients</th>
                  <td>{{context.num_patients}}</td>
                </tr>
                <tr>
                  <th>Free Beds</th>
                  <td>{{context.free_beds}}</td>
                </tr>
                <tr>
                  <th>Number of Nurses</th>
                  <td>{{context.num_nurses}}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="Card">
        <div class="Header">Patients</div>
        <div class="Body">
          <table class="ListTable">
            <thead>
              <th>#</th>
              <th>Name</th>
              <th>Age</th>
              <th>Disease</th>
              <th>Actions</th>
            </thead>
            <tbody>
              {% for patient in context.patients %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{patient.name}}</td>
                <td>{{patient.age}}</td>
                <td>{{patient.disease}}</td>
                <td>
                  <button id="#viewButton1">
                    <a href="{% url 'entities:detail_patient' pk=patient.id %}"
                      >View</a
                    >
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="Card">
        <div class="Header">Nurses</div>
        <div class="Body">
          <table class="ListTable">
            <thead>
              <th>#</th>
              <th>Name</th>
              <th>Age</th>
              <th>Experience</th>
              <th>Salary</th>
              <th>Actions</th>
            </thead>
            <tbody>
              {% for nurse in context.nurses %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{nurse.name}}</td>
                <td>{{nurse.age}}</td>
                <td>{{nurse.experience}}</td>
                <td>{{nurse.salary}}</td>
                <td>
                  <button id="#viewButton1">
                    <a href="{% url 'entities:detail_nurse' pk=nurse.id %}"
                      >View</a
                    >
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  {% comment %}
  <div class="Modal">
    <div class="ModalCard">
      <div class="Header">Edit Doctor</div>
      <div class="Body">
        <form class="Form">
          <div class="InputGroup">
            <label for="name">Name:</label>
            <input id="name" value="Eirini Mavrogeorgi" type="text" />
          </div>
          <div class="InputGroup">
            <label for="age">Age:</label>
            <input id="age" value="62" type="number" />
          </div>
          <div class="InputGroup">
            <label for="experience">Experience:</label>
            <input id="experience" value="25" type="number" />
          </div>
          <div class="InputGroup">
            <label for="salary">Salary:</label>
            <input id="salary" value="3500" type="number" />
          </div>
        </form>
      </div>
      <div class="Actions">
        <button class="Danger">Cancel</button>
        <button class="Success">Submit</button>
      </div>
    </div>
  </div>
  {% endcomment %}
</div>
{% endblock %}